/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: CCU4 PWM Example
*              for ModusToolbox.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"

/*******************************************************************************
* Macros
******************************************************************************/
/* Defines priority level of the period match event interrupt */
#define PWM_0_PERIOD_MATCH_EVENT_PRIORITY 63

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. It sets up and starts a CCU4 timer that triggers a 
* periodic interrupt based on the compare match. 
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /*Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Set NVIC priority */
    NVIC_SetPriority(PWM_0_PERIOD_MATCH_EVENT_IRQN, NVIC_EncodePriority(NVIC_GetPriorityGrouping(), PWM_0_PERIOD_MATCH_EVENT_PRIORITY, 0));

    /* Enable IRQ */
    NVIC_EnableIRQ(PWM_0_PERIOD_MATCH_EVENT_IRQN);

    /* Start the timer */
    XMC_CCU4_SLICE_StartTimer(PWM_0_HW);

    while (1);
}

/*******************************************************************************
* Function Name: PWM_0_PERIOD_MATCH_EVENT_HANDLER
********************************************************************************
* Summary:
* This is the interrupt handler function for the CCU4 compare match interrupt.
* It clears the event flag and restarts the timer. 
*
* Parameters:
*  none
*
* Return:
*  void
*
*******************************************************************************/
void PWM_0_PERIOD_MATCH_EVENT_HANDLER(void)
{
    /* Clear pending interrupt */
    XMC_CCU4_SLICE_ClearEvent(PWM_0_HW, XMC_CCU4_SLICE_IRQ_ID_PERIOD_MATCH);

    /* Restart the Timer using SCU.GSC40 signal*/
    XMC_SCU_SetCcuTriggerLow(XMC_SCU_CCU_TRIGGER_CCU40);
    XMC_SCU_SetCcuTriggerHigh(XMC_SCU_CCU_TRIGGER_CCU40);
}

/* [] END OF FILE */
